### ISSUE TITLE
How do I add Search, OrderBy, and Pagination Functionality?

### ISSUE THREAD

**Issue by barrydoyle18** [bmvr/MVC_BOOTGRID_EXAMPLE#1]
Hey man, I appreciated the solution but I need to implement Search, OrderBy and Pagination Functionality and I'm having a lot of trouble doing this. What needs to be done there?

**Comment by bmvr** [comment]
To answer your question I need to understand first, where do you want to apply the search etc.
You get the entire list from your WebServices or whatever and implement the pagination later, or you want to apply pagination when you're collecting the data from the database, by giving the parameters such as search, pagination in your db query?

**Comment by barrydoyle18** [comment]
It was going to be for applying it to the entire list as is but I figured it out.

**Comment by bmvr** [comment]
Good. I was preparing an example. Basically use skip/take in your list
